name: Update Fork

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the action once per day at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: Andreikap23/Shadowrocket-Rules-For-Russia
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up upstream
        run: |
          git remote add upstream https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
