name: Update Fork

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the action once per day at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Andreikap23/Shadowrocket-Rules-For-Russia
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git configuration
        run: |
          git config --global user.email andreikap23@gmail.com
          git config --global user.name Andreikap23

      - name: Set up upstream
        run: |
          git remote add upstream https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever.git
          git fetch upstream
          git checkout release || git checkout -b release

      - name: Merge upstream changes
        run: |
          git merge upstream/release --allow-unrelated-histories
          git push origin release

      - name: Remove existing AdBlocker.list
        run: |
          if [ -f AdBlocker.list ]; then
            rm AdBlocker.list
          fi

      - name: Duplicate and rename file
        run: |
          cp sr_ad_only.conf AdBlocker.list
          git add AdBlocker.list
          git commit -m "Add AdBlocker.list"
          git push origin release
